import 'dotenv/config';
import { toSheetsRow } from '../src/lib/integrations/sheets/map-row';
import type { RegistrationForSheetRow } from '../src/lib/integrations/sheets/map-row';

const samples: RegistrationForSheetRow[] = [
  {
    id: 'reg_ani_sargsyan',
    createdAt: new Date('2026-09-16T07:20:00.000Z'),
    firstName: 'Անի',
    lastName: 'Սարգսյան',
    email: 'ani.sargsyan@example.com',
    phone: '+37491234567',
    locale: 'hy',
    sourceSystem: 'TOON_EXPO',
    sourceRegistrationId: null,
    utmSource: 'facebook',
    utmMedium: 'cpc',
    utmCampaign: 'toon_expo_2026',
    ticketCode: 'TEANI7K2M9P',
    attendanceStatus: 'NOT_VISITED',
    emailDeliveryStatus: 'SENT',
    formVersion: '2026-vis-reg-v2',
    formChannel: 'GENERAL',
    answers: {
      ageBand: '25_34',
      residence: 'armenia',
      residenceDetail: 'yerevan',
      visitPurpose: 'own_residence',
      interestType: 'apartment',
      locationSeek: 'yerevan',
      yerevanDistricts: ['kentron', 'arabkir'],
      areaSqm: '60_80',
      purchaseMethod: 'mortgage',
      monthlyBudget: '300_500',
      decisionStage: 'active_search',
      purchaseHorizon: '6_12',
      newsletter: true,
    },
  },
  {
    id: 'reg_davit_hakobyan',
    createdAt: new Date('2026-09-16T08:05:00.000Z'),
    firstName: 'Դավիթ',
    lastName: 'Հակոբյան',
    email: 'davit.hakobyan@example.com',
    phone: '+37493445778',
    locale: 'hy',
    sourceSystem: 'TOON_EXPO',
    sourceRegistrationId: null,
    utmSource: 'instagram',
    utmMedium: 'social',
    utmCampaign: 'open_doors',
    ticketCode: 'TEDAV4H8Q1R',
    attendanceStatus: 'VISITED',
    emailDeliveryStatus: 'SENT',
    formVersion: '2026-vis-reg-v2',
    formChannel: 'GENERAL',
    answers: {
      ageBand: '35_44',
      residence: 'armenia',
      residenceDetail: 'gyumri',
      visitPurpose: 'investment',
      interestType: ['apartment', 'commercial'],
      locationSeek: 'yerevan',
      yerevanDistricts: ['davtashen', 'ajapnyak'],
      areaSqm: '80_100',
      purchaseMethod: 'cash',
      decisionStage: 'comparing',
      investmentPropertyType: 'apartment',
      investmentMarket: 'yerevan',
      investmentGoal: 'rental_income',
      investmentTimeline: '1_2y',
      investmentBudgetUsd: '80000_120000',
      priorInvestmentExperience: 'some',
      newsletter: true,
    },
  },
  {
    id: 'reg_mariam_avetisyan',
    createdAt: new Date('2026-09-15T14:40:00.000Z'),
    firstName: 'Մարիամ',
    lastName: 'Ավետիսյան',
    email: 'mariam.avet@example.com',
    phone: '+37455612309',
    locale: 'hy',
    sourceSystem: 'TOON_EXPO',
    sourceRegistrationId: null,
    utmSource: 'google',
    utmMedium: 'search',
    utmCampaign: 'brand',
    ticketCode: 'TEMAR2N6W3C',
    attendanceStatus: 'NOT_VISITED',
    emailDeliveryStatus: 'PENDING',
    formVersion: '2026-vis-reg-v2',
    formChannel: 'GENERAL',
    answers: {
      ageBand: '18_24',
      residence: 'armenia',
      residenceDetail: 'yerevan',
      visitPurpose: 'own_residence',
      interestType: 'apartment',
      locationSeek: 'yerevan',
      yerevanDistricts: ['malatia_sebastia'],
      areaSqm: '40_60',
      purchaseMethod: 'mortgage',
      monthlyBudget: '200_300',
      decisionStage: 'researching',
      purchaseHorizon: '12_plus',
      newsletter: false,
    },
  },
  {
    id: 'reg_armen_grigoryan',
    createdAt: new Date('2026-09-15T12:15:00.000Z'),
    firstName: 'Արմեն',
    lastName: 'Գրիգորյան',
    email: 'armen.g@example.com',
    phone: '+37477901224',
    locale: 'ru',
    sourceSystem: 'TOON_EXPO',
    sourceRegistrationId: null,
    utmSource: 'referral',
    utmMedium: 'friend',
    utmCampaign: null,
    ticketCode: 'TEARM9P5L2X',
    attendanceStatus: 'VISITED',
    emailDeliveryStatus: 'SENT',
    formVersion: '2026-vis-reg-v2',
    formChannel: 'GENERAL',
    answers: {
      ageBand: '45_54',
      residence: 'abroad',
      visitPurpose: 'investment',
      interestType: 'house',
      abroadCountries: ['russia'],
      locationSeek: 'marz',
      marzRegions: ['kotayk', 'ararat'],
      areaSqm: '100_plus',
      purchaseMethod: 'cash',
      decisionStage: 'ready',
      investmentPropertyType: 'house',
      investmentMarket: 'armenia',
      investmentGoal: 'family_and_invest',
      investmentTimeline: 'under_1y',
      investmentBudgetUsd: '150000_250000',
      priorInvestmentExperience: 'experienced',
      interestedWhere: 'kotayk',
      purchaseHorizon: '0_6',
      newsletter: true,
    },
  },
  {
    id: 'reg_lilit_ghazaryan',
    createdAt: new Date('2026-09-14T06:50:00.000Z'),
    firstName: 'Լիլիթ',
    lastName: 'Ղազարյան',
    email: 'lilit.gh@example.com',
    phone: '+37498333140',
    locale: 'hy',
    sourceSystem: 'TOON_EXPO',
    sourceRegistrationId: null,
    utmSource: 'facebook',
    utmMedium: 'cpc',
    utmCampaign: 'retarget',
    ticketCode: 'TELIL1V8B4Z',
    attendanceStatus: 'NOT_VISITED',
    emailDeliveryStatus: 'SENT',
    formVersion: '2026-vis-reg-v2',
    formChannel: 'GENERAL',
    answers: {
      ageBand: '25_34',
      residence: 'armenia',
      residenceDetail: 'vanadzor',
      visitPurpose: 'own_residence',
      interestType: 'apartment',
      locationSeek: 'yerevan',
      yerevanDistricts: ['kanaker_zeytun', 'nor_nork'],
      areaSqm: '60_80',
      purchaseMethod: 'mortgage',
      monthlyBudget: '300_500',
      decisionStage: 'active_search',
      purchaseHorizon: '6_12',
      newsletter: true,
    },
  },
];

async function main(): Promise<void> {
  const url = process.env.SHEETS_WEBHOOK_URL;
  const secret = process.env.SHEETS_WEBHOOK_SECRET;
  if (!url || !secret) {
    throw new Error('SHEETS_WEBHOOK_URL / SHEETS_WEBHOOK_SECRET missing');
  }

  const rows = samples.map((sample) => toSheetsRow(sample));
  const headers = rows[0]?.headers ?? [];
  const body = {
    secret,
    action: 'reset',
    channel: 'GENERAL',
    tab: 'Ընդհանուր',
    headers,
    rows: rows.map((row) => row.values),
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(120_000),
  });
  const text = await response.text();
  console.log(JSON.stringify({ status: response.status, body: text.slice(0, 500) }));
}

void main();
